-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfyGZgqG+deTmT/I/
1gGKqIOJjG59LCWTHDpWf8uqwHKgCgYIKoZIzj0DAQehRANCAATmTWdF+QQHCw96
F3qhqRFYpCj48KR+AuNXfDYeNGoEh0R3XZxU5v7K9RpQ4N/uS7riFT9BcKDjxXqP
K/CMZlrk
-----END PRIVATE KEY-----